title: bajor.dev
description: Personal dev blog
url: "https://bajor.dev"
baseurl: ""
markdown: kramdown
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Makefile
  - README.md
  - ARCHITECTURE_DIFF.md
